# Generated by Django 4.1.2 on 2024-06-22 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_categoria_productos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='market.usuario'),
        ),
    ]
