# Generated by Django 4.1.2 on 2024-06-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_fecha_cuanta_usuario_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritos',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombreUsuario',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
    ]
