# Generated by Django 4.1.2 on 2024-06-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_favoritos_producto_remove_favoritos_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
