# Generated by Django 4.1.2 on 2024-06-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
