# Generated by Django 5.0.6 on 2024-07-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_registrocompras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='fecha_expiracion',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='anioExpiracion',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='mesExpiracion',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
