# Generated by Django 5.0.6 on 2024-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_remove_metodopago_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
