# Generated by Django 5.0.6 on 2024-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_direccion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
