# Generated by Django 5.0.6 on 2024-07-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
